"""empty message

Revision ID: a4a3df58b532
Revises: e6ffaf74532d
Create Date: 2024-06-12 19:01:39.483459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4a3df58b532'
down_revision = 'e6ffaf74532d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments_criminals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('criminal_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(), nullable=False),
    sa.Column('comment_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['criminal_id'], ['criminals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments_missing_persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('missing_person_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(), nullable=False),
    sa.Column('comment_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['missing_person_id'], ['missing_persons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved_criminals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('criminal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['criminal_id'], ['criminals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved_missing_persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('missing_person_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['missing_person_id'], ['missing_persons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stories_criminals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('creation_date', sa.Date(), nullable=False),
    sa.Column('modification_date', sa.Date(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('criminal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['criminal_id'], ['criminals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stories_missing_persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('creation_date', sa.Date(), nullable=False),
    sa.Column('modification_date', sa.Date(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('missing_person_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['missing_person_id'], ['missing_persons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('stories__missing__persons')
    op.drop_table('saved__criminals')
    op.drop_table('saved__missing__persons')
    op.drop_table('comments__criminals')
    op.drop_table('stories__criminals')
    op.drop_table('comments__missing__persons')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments__missing__persons',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('missing_person_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comment', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('comment_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['missing_person_id'], ['missing_persons.id'], name='comments__missing__persons_missing_person_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='comments__missing__persons_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='comments__missing__persons_pkey')
    )
    op.create_table('stories__criminals',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('body', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('prompt', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('creation_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('modification_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('criminal_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['criminal_id'], ['criminals.id'], name='stories__criminals_criminal_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='stories__criminals_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='stories__criminals_pkey')
    )
    op.create_table('comments__criminals',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('criminal_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comment', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('comment_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['criminal_id'], ['criminals.id'], name='comments__criminals_criminal_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='comments__criminals_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='comments__criminals_pkey')
    )
    op.create_table('saved__missing__persons',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('missing_person_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['missing_person_id'], ['missing_persons.id'], name='saved__missing__persons_missing_person_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='saved__missing__persons_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='saved__missing__persons_pkey')
    )
    op.create_table('saved__criminals',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('criminal_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['criminal_id'], ['criminals.id'], name='saved__criminals_criminal_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='saved__criminals_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='saved__criminals_pkey')
    )
    op.create_table('stories__missing__persons',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('body', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('prompt', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('creation_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('modification_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('missing_person_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['missing_person_id'], ['missing_persons.id'], name='stories__missing__persons_missing_person_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='stories__missing__persons_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='stories__missing__persons_pkey')
    )
    op.drop_table('stories_missing_persons')
    op.drop_table('stories_criminals')
    op.drop_table('saved_missing_persons')
    op.drop_table('saved_criminals')
    op.drop_table('comments_missing_persons')
    op.drop_table('comments_criminals')
    # ### end Alembic commands ###
