"""empty message

Revision ID: b395d27eae99
Revises: 48c188a28992
Create Date: 2024-06-10 19:56:33.068519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b395d27eae99'
down_revision = '48c188a28992'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('criminals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('nationality', sa.String(), nullable=False),
    sa.Column('sex', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('caution', sa.String(), nullable=False),
    sa.Column('race', sa.String(), nullable=False),
    sa.Column('remarks', sa.String(), nullable=False),
    sa.Column('hair_raw', sa.String(), nullable=False),
    sa.Column('possible_countries', sa.String(), nullable=False),
    sa.Column('aliases', sa.String(), nullable=False),
    sa.Column('place_of_birth', sa.String(), nullable=False),
    sa.Column('dates_of_birth_used', sa.String(), nullable=False),
    sa.Column('eyes', sa.String(), nullable=False),
    sa.Column('subjects', sa.String(), nullable=False),
    sa.Column('images', sa.String(), nullable=False),
    sa.Column('field_offices', sa.String(), nullable=False),
    sa.Column('reward_text', sa.String(), nullable=False),
    sa.Column('weight', sa.String(), nullable=False),
    sa.Column('favourites_amount', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commentaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('criminal_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(), nullable=False),
    sa.Column('comment_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['criminal_id'], ['criminals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved__criminals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('criminal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['criminal_id'], ['criminals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('creation_date', sa.Date(), nullable=False),
    sa.Column('modification_date', sa.Date(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('criminal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['criminal_id'], ['criminals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('surname', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('description', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('avatar', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')
        batch_op.drop_column('avatar')
        batch_op.drop_column('description')
        batch_op.drop_column('surname')
        batch_op.drop_column('name')

    op.drop_table('stories')
    op.drop_table('saved__criminals')
    op.drop_table('commentaries')
    op.drop_table('criminals')
    # ### end Alembic commands ###
