"""empty message

Revision ID: e6ffaf74532d
Revises: b395d27eae99
Create Date: 2024-06-12 18:46:08.012571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6ffaf74532d'
down_revision = 'b395d27eae99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('missing_persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('nationality', sa.String(), nullable=False),
    sa.Column('sex', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('race', sa.String(), nullable=False),
    sa.Column('remarks', sa.String(), nullable=False),
    sa.Column('hair_raw', sa.String(), nullable=False),
    sa.Column('possible_countries', sa.String(), nullable=False),
    sa.Column('place_of_birth', sa.String(), nullable=False),
    sa.Column('dates_of_birth_used', sa.String(), nullable=False),
    sa.Column('eyes', sa.String(), nullable=False),
    sa.Column('subjects', sa.String(), nullable=False),
    sa.Column('images', sa.String(), nullable=False),
    sa.Column('field_offices', sa.String(), nullable=False),
    sa.Column('reward_text', sa.String(), nullable=False),
    sa.Column('weight', sa.String(), nullable=False),
    sa.Column('favourites_amount', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments__criminals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('criminal_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(), nullable=False),
    sa.Column('comment_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['criminal_id'], ['criminals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments__missing__persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('missing_person_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(), nullable=False),
    sa.Column('comment_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['missing_person_id'], ['missing_persons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved__missing__persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('missing_person_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['missing_person_id'], ['missing_persons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stories__criminals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('creation_date', sa.Date(), nullable=False),
    sa.Column('modification_date', sa.Date(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('criminal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['criminal_id'], ['criminals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stories__missing__persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('creation_date', sa.Date(), nullable=False),
    sa.Column('modification_date', sa.Date(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('missing_person_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['missing_person_id'], ['missing_persons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('commentaries')
    op.drop_table('stories')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('body', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('prompt', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('creation_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('modification_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('criminal_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['criminal_id'], ['criminals.id'], name='stories_criminal_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='stories_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='stories_pkey')
    )
    op.create_table('commentaries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('criminal_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comment', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('comment_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['criminal_id'], ['criminals.id'], name='commentaries_criminal_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='commentaries_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='commentaries_pkey')
    )
    op.drop_table('stories__missing__persons')
    op.drop_table('stories__criminals')
    op.drop_table('saved__missing__persons')
    op.drop_table('comments__missing__persons')
    op.drop_table('comments__criminals')
    op.drop_table('missing_persons')
    # ### end Alembic commands ###
